### ISSUE TITLE
Variable length relationships

### ISSUE THREAD

**Issue by g3rd** [emehrkay/Pypher#12]
How would you write out the example from the [Neo4j docs](https://neo4j.com/docs/developer-manual/current/cypher/clauses/match/#varlength-rels)?

```cypher
MATCH (martin { name: 'Charlie Sheen' })-[:ACTED_IN*1..3]-(movie:Movie)
RETURN movie.title
```

**Comment by g3rd** [comment]
Or a fixed length:

```cypher
MATCH (martin { name: 'Charlie Sheen' })-[:ACTED_IN*3]-(movie:Movie)
RETURN movie.title
```

**Comment by emehrkay** [comment]
Good catch. With backticks would it be: 

[:`ACTED_IN`*3]


I am looking at the documentation to better understand variable length matching. 

I think we’ll be able to easily do something like

```python
p.node().rel(labels=‘ACTED_IN*3’).node()
```

And get “()-[:`ACTED_IN`*3]-()”

What do you think of that?

**Comment by emehrkay** [comment]
Or can labels have asterisks in them? If they can, we may need to manually use a Label object and add a variable_length arg like this

```python
p.node.rel(labels=Label(‘ACTED_IN’, length=3)).node
```

**Comment by g3rd** [comment]
@emehrkay The PR I opened, added `min_hops` and `max_hops`, I would be down for the `length`

**Comment by g3rd** [comment]
Adding it to the label would get tricky when the labels are in a list

**Comment by g3rd** [comment]
I also updated tests, and the readme in that PR.

**Comment by g3rd** [comment]
@emehrkay 0.9.2?

When are you thinking of pushing up to pypi?

**Comment by emehrkay** [comment]
I will upload it tonight.
