### ISSUE TITLE
Plugin Compatibility?

### ISSUE THREAD

**Issue by ProjectCheshire** [emehrkay/Pypher#14]
Love it, came here via Neo4J blog. 
Is it possible to use Pypher with APOC or spatial or other jar plugins? Is there a recommended 'extension' path for adding that support?

Cheers

**Comment by g3rd** [comment]
Hi @ProjectCheshire 

I use the APOC functions. I follow along with: https://github.com/emehrkay/Pypher/issues/8

For example, I use `apoc.text.join`, `apoc.date.convert`, and `apoc.date.currentTimestamp` a good bit. (Although, those two date functions will soon be replaced with the native Neo4j datetime support)

Before my Pypher query I do:

```
create_function('apoc_text_join', {'name': 'apoc.text.join'}, func_raw=True)
create_function('apoc_date_convert', {'name': 'apoc.date.convert'})
create_function('apoc_date_current_timestamp', {'name': 'apoc.date.currentTimestamp'})
```

Then in my query to use I would do:
```
p.Match.node('u', 'User')
p.Return.apoc_text_join(__.List(__.u.__first_name__, __.u.__last_name__), "' '").alias('name')
```

**Comment by emehrkay** [comment]
Ohh that makes so much sense. Thanks @g3rd.

Let me ask you both: is there something that could be included in the readme to make this clearer?

**Comment by g3rd** [comment]
I was thinking about adding a separate doc that has examples of different type of queries. So it can show how to write different types. Just haven't gotten around to it.
