### ISSUE TITLE
Importance of calling str(q)

### ISSUE THREAD

**Issue by jurrian** [emehrkay/Pypher#15]
Could you include in the documentation the importance of calling `str(q)`?
I was aware that `str(q)` has to be called before handing it off to the Neo driver.

However, at some point I failed to make that call, but I did a `print` somewhere so it still worked.
It took me a long time before I realized my mistake. Especially since Pycharm debugger _did_ call `str`, which made it very confusing to know what went wrong.

**Comment by emehrkay** [comment]
Thanks for the feedback, I added a note in the readme. Does this make it a bit clearer? https://github.com/emehrkay/Pypher/commit/ed83579ad2de77b98efed0727507f72679370ced

**Comment by jurrian** [comment]
Perfect. Much appreciated!
