### ISSUE TITLE
Cannot assign 'zero' values 

### ISSUE THREAD

**Issue by alexlitvinenko** [emehrkay/Pypher#17]
https://github.com/emehrkay/Pypher/blob/ed83579ad2de77b98efed0727507f72679370ced/pypher/builder.py#L757

Given pypher: `p.SET.n.property('a_property') == 0.0`
Actual cypher will be the following: `SET n.a_property =`
Expected cypher: `SET n.a_property = 0.0`

**Comment by emehrkay** [comment]
That is a huge oversight. I have fixed it with 0.11.1. I actually do not know why I have that check in the code, none of my tests address the else case. I will add some code coverage tooling to the stack to prevent that situation in the future.

Thanks,
Mark
