### ISSUE TITLE
Operator precedence?

### ISSUE THREAD

**Issue by alexlitvinenko** [emehrkay/Pypher#18]
Is there way to express operator precedence in Pypher?
I need to express something like: 
`MATCH (n) WHERE (n.property_a = "foo" OR n.property_a = "bar") AND n.property_b = 1 RETURN n`

**Comment by emehrkay** [comment]
Im sorry for the delay, the best thing that I could come up with was using `RAW` to add actual parenthesis

```p.MATCH.node('n').WHERE.RAW('(', __.n.__property_a__ == 'foo', __.OR, __.n.__property_b__ == 'bar', ')').AND(__.n.__property_b__ == 1).RETURN.n```
 
![screen shot 2018-08-26 at 4 23 39 pm](https://user-images.githubusercontent.com/24242/44632653-6ad8c580-a94c-11e8-8894-0aea5b34c3a0.png)

Maybe a `Group` object could be added in the future that would simply automatically wrap its contents in parens. You may also be able to overload the `WHERE` statement to make it a function (this is better than raw to me)

```python
from pypher.builder import create_function
create_function('WHERE_GROUP', {'name': 'WHERE'})

p = Pypher()
p.WHERE_GROUP(__.n.__prop_a__ == 'foo', __.OR, __.n.__prop_b__ == 'bar').AND.n.__prop_b__ == 'baz'
p.RETURN.n

print(str(p))
```

**Comment by emehrkay** [comment]
Okay, new in version `0.13.0` are `Conditional` objects (`Conditional`, `ConditionalAND`, and `ConditionalOR`) https://github.com/emehrkay/Pypher#conditionals

Usage is pretty straight forward:

```python
p.MATCH.node('n').WHERE.COR(__.n.__property_a__ == 'foo', __.n.__property_b__ == 'bar').AND(__.n.__property_b__ == 1).RETURN.n
```

![screen shot 2018-08-26 at 11 36 45 pm](https://user-images.githubusercontent.com/24242/44639238-eb1d1c00-a988-11e8-85a6-28d3789ed1bf.png)
