### ISSUE TITLE
[On Create] AttributeError: 'str' object has no attribute

### ISSUE THREAD

**Issue by tolmanam** [emehrkay/Pypher#22]
I've pip installed python-cypher==0.14.3 and was trying to run through some of the examples to figure out how this module works when I ran into an issue.

``` python
p = Pypher()
p.MERGE.node('user', 'User', Id=456).ON.CREATE.user.SET(__.user.__Name__ == 'Jim')
print(p)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-25-a88f1b7b8be9> in <module>
      1 p = Pypher()
----> 2 p.MERGE.node('user', 'User', Id=456).ON.CREATE.user.SET(__.user.__Name__ == 'Jim')
      3 print(p)

AttributeError: 'str' object has no attribute 'user'
```

**Comment by emehrkay** [comment]
I am unable to reproduce this bug.

Using the tester.py script with 0.14.3, I copied and pasted your query

<img width="1032" alt="screen shot 2018-11-03 at 9 42 33 pm" src="https://user-images.githubusercontent.com/24242/47959071-6e727380-dfb1-11e8-9a1f-01370db642b8.png">

So I believe that the `__` variable is a string in your codebase. You can always do `whatever = Anon() ... whatever.user.__Name__ ...`

**Comment by tolmanam** [comment]
Ok... I see what I did wrong.

I orignally created a new python file (pypher_test.py) with the following lines.
``` python
#!/bin/env python

from pypher import Pypher

p = Pypher()
p.MERGE.node('user', 'User', Id=456).ON.CREATE.user.SET(__.user.__Name__ == 'Jim')
print(p)
```

The results from runing this script are as follows.
``` shell
$ python --version
Python 3.6.5 :: Anaconda, Inc.
$ python pypher_test.py 
Traceback (most recent call last):
  File "pypher_test.py", line 10, in <module>
    p.MERGE.node('user', 'User', Id=456).ON.CREATE.user.SET(__.user.__Name__ == 'Jim')
NameError: name '__' is not defined
```

My problem was that I neglected to import the '__' from pypher as well.
