### ISSUE TITLE
None in Python and NULL in Pypher inconsistency?

### ISSUE THREAD

**Issue by ianedwardthomas** [emehrkay/Pypher#27]
I think I've found an inconsistency in handling NULL attributes in Pypher:
```
p = Pypher()
p.MERGE.node('foo', 'baz').OnCreate.SET(__.bar == None)
cprint(p)
```
Produces:
```
Cypher:
MERGE (foo:`baz`) ON CREATE SET bar = $NEO_65fc3_0
Bound Params:
{'NEO_65fc3_0': 'null'}
```
Note that `bar` is a string containing the word `null`.

But the equivalent code in CYPHER for the same intent would be
```
MERGE (foo:`baz`) ON CREATE SET foo.bar == NULL
```

which creates node with no attribute `bar`,

rather than this
```
MERGE (foo:`baz`) ON CREATE SET foo.bar == 'null'
```
which creates node with attribute bar = 'null'
which is what the Pypher version does.  I'm trying to create equivalent Pypher so that no attribute in neo4j is created when the Python type is None.  Am I just confused?

**Comment by ianedwardthomas** [comment]
Ah, but I've found now that 
```
p = Pypher()
p.MERGE.node('foo','baz').OnCreate.SET(__.bar == __.NULL)
cprint(p)
```
Produces the correct output.  So the lesson here is to stay in the Pypher world and not in the python world :)

**Comment by emehrkay** [comment]
Another great catch. It could probably check if the value is None and set it to be `__.NULL` at the very top of the `Param.bind_param` method

**Comment by emehrkay** [comment]
0.16.1 should fix this. See:

https://github.com/emehrkay/Pypher/blob/9dfeb3004e3cc135c714918a65901aa4fc7bace8/pypher/test/builder.py#L1412

and

https://github.com/emehrkay/Pypher/blob/9dfeb3004e3cc135c714918a65901aa4fc7bace8/pypher/test/builder.py#L788

**Comment by ianedwardthomas** [comment]
Looks good. Thanks.
