### ISSUE TITLE
simple README fix

### ISSUE THREAD

**Issue by dfgit** [emehrkay/Pypher#3]
"lables" should be "labels" in:  

p.MATCH.node('mark', labels='Person').rel(labels='knows').node('mikey', **lables**=['Cat', 'Animal'])

**Comment by emehrkay** [comment]
Thank you. I will go through each example and run them in the interpreter to ensure that both the code and expected output is correct.

**Comment by Pawamoy** [comment]
There are other typos like `MATACH` (my favorite one), `CAPATILIZE`, `referece`.
