### ISSUE TITLE
Cannot set "list" in as property value

### ISSUE THREAD

**Issue by gb08** [emehrkay/Pypher#31]
unable to build cypher query to set "list" type value in property.
set entity.birth_date = coalesce(VALUE + entity.birth_date, entity.birth_date , [] + VALUE)

What I've tried:
from pypher import Pypher, __
p = Pypher()
node_gr = dict()
node_gr['name'] = 'XYZ'
p.Merge.node('ent', **node_gr)
p.SET(\__.ent.__birth_place\_\_ == __.COALESCE(\_\_.ent.\_\_birth_place\_\_+ 
VALUE,\_\_.ent.\_\_birth_place\_\_,[VALUE]))

Error:
python3.6/site-packages/pypher/builder.py in bind_param(self, value, name)
    196                     name = k
    197                     break
--> 198         elif bind and value in self._bound_params.keys():
    199             for k, v in self._bound_params.items():
    200                 if k == value:

TypeError: unhashable type: 'list'

**Comment by emehrkay** [comment]
This slipped under my radar. Did you want the brackets to show up in the resulting Cypher? If so, use the `List` class:

```python
from pypher import Pypher, __
VALUE = 123
p = Pypher()
node_gr = dict()
node_gr['name'] = 'XYZ'
p.Merge.node('ent', **node_gr)
p.SET(__.ent.__birth_place__ == __.COALESCE(__.ent.__birth_place__+
VALUE,__.ent.__birth_place__, __.List(VALUE)))

str(p) 
# MERGE (ent {`name`: $nameb5401_0}) SET ent.`birth_place` = coalesce(ent.`birth_place` + $NEO_b5401_1, ent.`birth_place`,  [$NEO_b5401_1])
# {'NEO_b5401_1': 123, 'nameb5401_0': 'XYZ'}
```

**Comment by gb08** [comment]
Yes, Thank you!

What if I want to set property with list as a value. 
**p.SET(__.ent.__xyz__ == var1)**

where var1 = ['a', 'b'] (var1 is already in list python format)
