### ISSUE TITLE
Howto do WHERE

### ISSUE THREAD

**Issue by hudecof** [emehrkay/Pypher#34]
Hi,

I'm trying to write pypher statement for function like
```
def list(db: Graph, type: str=None, okres:str = None):
    q = Pypher()
    q.Match.node('school', labels='School')
    if type is not None:
        q.WHERE.school.property('type') == type
    if okres is not None:
        q.AND.school.property('okres') == okres
    q.RETURN.school
```

If both conditions are **NULL** it works.
If `type` is set nad `okres` is **NULL**, it works.

Otherwise it do not works.

Is there any smart way hw to write **WHERE** statment, when I do not known the number of condition before? Like chaining **AND**, using Partials ..

  regards
     Peter

**Comment by emehrkay** [comment]
I typically collect where clauses in a list and if that list has a length run a `ConditionalAND`

```python
...
wheres = []

if type:
    wheres.append(__.school.property('type') == type)

if okres:
    wheres.append(__.school.property('okres') == okres)

if len(wheres):
    q.WHERE.CAND(*wheres)

q.RETURN.school
```

**Comment by hudecof** [comment]
great, thanks
