### ISSUE TITLE
Change `min_hops` and `max_hops` semantics

### ISSUE THREAD

**Issue by dconathan** [emehrkay/Pypher#36]
Currently the way to do "hops with no upper limit" is counterintuitive and seems like it's taking advantage of a bug... by "hops with no upper limit" I mean:

```cypher
MATCH (n)-[*1..]->(m) RETURN m
```
Currently, the only way to do this is:
```python
q = Pypher()
q.MATCH.node("n").rel_out(min_hops=1, max_hops="").node("m")
```
Whereas I would expect:
```python
q = Pypher()
q.MATCH.node("n").rel_out(min_hops=1).node("m")
```
Because it's saying "I am specifying the `min_hops` and I am not specifying `max_hops`".  In general the semantics of:
> To create a fixed length relationship, use either `min_hops` or `max_hops`, or set both to the same number

Is not obvious or intuitive.

## Proposal

A new param called `hops` for specifying a single hop number.  `min_hops` and `max_hops` are reserved for specifying variable length relationships.  If `hops` is specified, and one (or both) of `min_hops` and `max_hops` is specified, an error is raised.  If just one of `min_hops` or `max_hops` is specified, then the range is only bounded on that side.

Examples:
```python
q = Pypher()
q.MATCH.node("n").rel_out(hops=2).node("m")
# MATCH (n)-[*2]->(m)
````
```python
q = Pypher()
q.MATCH.node("n").rel_out(min_hops=2).node("m")
# MATCH (n)-[*2..]->(m)
````
```python
q = Pypher()
q.MATCH.node("n").rel_out(min_hops=2, max_hops=3).node("m")
# MATCH (n)-[*2..3]->(m)
````
```python
q = Pypher()
q.MATCH.node("n").rel_out(hops=1, max_hops=3).node("m")
# raises error
````

If this is agreeable, I'm happy to put together a PR.

**Comment by emehrkay** [comment]
I think this looks good. Sorry for the delay, the email was sent to junk.

**Comment by emehrkay** [comment]
I merged this, but never updated the package. It should be in pypi now.
