### ISSUE TITLE
missing aggregate functions

### ISSUE THREAD

**Issue by hudecof** [emehrkay/Pypher#39]
Hi,

I'm mssing aggregate function like **max**.

PLease could someone provide an example? 

my query is 
`MATCH (i:iPerf)<-[r:HasiPerf]-(s:School) RETURN s.eduid as eduid , max(i.time) as time ORDER BY time desc`

   regards
    hudecof

**Comment by emehrkay** [comment]
Yes. Somehow `max` is missing. Do you know of any other missing functions? I will add them. In the meantime, you can use the create_function method to add it

```
create_function('MAX', {'name': 'max'}) 
p.max(9, 9)
```

![Screen Shot 2020-07-08 at 8 14 42 AM](https://user-images.githubusercontent.com/24242/86917518-2ba45f80-c0f3-11ea-8e43-bdce8e5e09bd.png)

**Comment by emehrkay** [comment]
I added `MAX` to release 0.18.0 and it is on pypi

**Comment by hudecof** [comment]
thanks
