### ISSUE TITLE
Multiple types for relationships

### ISSUE THREAD

**Issue by Pawamoy** [emehrkay/Pypher#4]
I think your code will not work with multiple types for relationships.

Since both `Node` and `Relationship` are children of `Entity`, and `Entity` uses `:` to delimit labels, your rels will be written like nodes, i.e. `[name:TYPE1:TYPE2]` which I think is not supported. Instead, it should be `[name:TYPE1|TYPE2]`. It's because a rel in Neo4j can have only one type, so you can only match them with OR, not AND.

(**Inversadly**, nodes only support AND and not OR, so you cannot do `(name:LABEL1|LABEL2)`, only `(name:LABEL1:LABEL2)`).

If you separate the related code from Entity into Node and Relationship, maybe you could also rename Relationship's `labels` to `types`, to better match the Neo4j concepts :smile:

**Comment by emehrkay** [comment]
Great catch.l, I need more scrutinization like this as I’m fairly new to Cypher/Neo4j. Thanks.  

I think that a potential solution is two fold. First the `Entity` would be updated to use actual `Label` objects for label representations. Second would be to update that `Label` class to allow for ‘and’ or ‘or’ chaining (with `Relationship` objects only allow for or)

With these two updates one could potentially write something like:

```python

p.relationship(labels=Label(‘Person’) | Label(‘Animal’))

# or
p.relationship(labels=(‘Person’, ‘Animal’))
```

Both would work the same under the hood. I’ll have to test that interface later

(Excuse the typos I’m on my phone)
