### ISSUE TITLE
Handling a list of dictionaries

### ISSUE THREAD

**Issue by bx-ali** [emehrkay/Pypher#41]
I was wondering if there is a cleaner way to handle a list of dictionaries 

```
    p = Pypher()
    batch = []
    for x in observations:
        batch.append(__.MAP(**x))

    return p.unwind(__.List(*batch))
```

above has been functional when the inputs looks like
`[{'x':1,'y':2},{'x':2,'y':4},...]`

wondering if I can avoid creating a new list of my existing list and then using the list function on it again as it seems a bit circular 
thank you in advance

**Comment by emehrkay** [comment]
I cant really think of a way to compress it. Well maybe you can hide the logic behind a custom Statement

```python
class ListDict(List):

    def __unicode__(self):
        args = []

        for arg in self.args:
            args.append(__.MAP(**arg))

        self.args = args
        return super().__unicode__()


# Attempt to use it
q = Pypher()
observations = [{'x':1,'y':2}, {'x':2,'y':4}]
q.ListDict(*observations)
print(str(q))
```
