### ISSUE TITLE
Problem with And operator

### ISSUE THREAD

**Issue by fanavarro** [emehrkay/Pypher#42]
Hi, I am trying to concatenate several filters in the where clause through And conditions, but I am getting a strange NULL in the middle of the query. For example:
```
builder = Pypher()
builder.Where.node('procedure').rel_out(labels='type').node(labels='A')
builder.And.node('procedure').rel_out(labels='type').node(labels='B')
print(str(builder))
```
Is resulting on:
`WHERE (procedure)-[:`type`]->(:`A`) AND NULL(procedure)-[:`type`]->(:`B`)`

How can I avoid this NULL appearing after the AND keyword?

Greetings!

**Comment by emehrkay** [comment]
AND is an operator and must be called with parens. https://github.com/emehrkay/Pypher#operators

```python
builder.AND(__.node('procedure')).rel_out(labels='type').node(...)
```

> The reason you're seeing NULL is because it is finding the `And` class and is looking for a static property that doesnt exist on it

**Comment by fanavarro** [comment]
Ok, thanks @emehrkay. I was a little bit confused because the OR condition did not include that NULL when using it in that way. Everything clear now, thanks again!
