### ISSUE TITLE
Support for union and call

### ISSUE THREAD

**Issue by fanavarro** [emehrkay/Pypher#43]
Hello, Im wondering if Pypher suports union and call statements. I would like to achieve something like this:
```
CALL{
	MATCH (result:`A`)<-[:`rel_a`]-(x) return result
	UNION
	MATCH (result:`B`)<-[:`rel_b`]-(x) return result
}
```
If not, I guess I can implement them through raw function. Am I right?

Thanks for your work,
greetings!

**Comment by emehrkay** [comment]
You can probably use `Projection`

```python
p.PROJECTION('CALL', __.MATCH.node('A').UNION.MATCH.node('B'))
```

![Screen Shot 2020-09-29 at 12 21 45 PM](https://user-images.githubusercontent.com/24242/94585751-70e9b080-024e-11eb-9815-15dcbe519c5d.png)

**Comment by fanavarro** [comment]
It worked, thanks!

**Comment by emehrkay** [comment]
It is also possible to write your own `Call` statement that way you won't need to always do the clunky `map_projection` call

```python
from pypher.builder import Pypher, MapProjection, __


class Call(MapProjection):

    def __init__(self, *args, **kwargs):
        super(Call, self).__init__('CALL', *args, **kwargs)


# Attempt to use it
q = Pypher()
q.Call(__.match.node('A').RETURN('A').union.match.node('B').RETURN('B'))
# q.Projection('CALL', __.match.node('A').RETURN('A').union.match.node('B').RETURN('B'))
x = str(q)
print(x)
```
