### ISSUE TITLE
Quoting label names

### ISSUE THREAD

**Issue by akloster** [emehrkay/Pypher#50]
I am trying to construct queries for another Cypher compatible database, specifically AgensGraph, and the first problem I ran into is the quotation of labels when creating nodes or edges.

The issue is that this particular dialect doesn't like the ` quotation mark, it would prefer double quotes or no quotes.

**Comment by emehrkay** [comment]
It makes sense to make the quotes configurable. It seems that Labels, Map keys, and Properties have them. I would do something like this:

```python
QUOTE = {
    'label': '`',
    'map_key': '`',
    'property': '`',
}
```

and it would be configurable at runtime. What do you think?

**Comment by emehrkay** [comment]
0.20.0 has been released with the update

```python
import pyper
pyper.builder.QUOTES['propery'] = '"' # this will quote properties with a " instead of `
```

**Comment by akloster** [comment]
But apparently it was also an issue of "Agensgraph" vs "Apache AGE", the latter now requires the ` form ...

Thank you for your reply!
