### ISSUE TITLE
Question: use with neo4j-driver

### ISSUE THREAD

**Issue by g3rd** [emehrkay/Pypher#6]
I'm using the Neo4j Python driver, example code below. The driver requires the params in Cypher to be surrounded by parentheses.

Is there a way to configure?

Thanks!
Chad.

```python
p = Pypher()
p.CREATE.node('user', 'User', Name='Jim')

 with driver.session() as  session:
       session.run(str(p), **dict(p.bound_params))
```

Raises:
```
neo4j.exceptions.CypherSyntaxError: Parentheses are required to identify nodes in patterns
```

**Comment by emehrkay** [comment]
I am not getting that error. 

Here is my code:

```python
from neo4j.v1 import GraphDatabase
from pypher.builder import Pypher

uri = "bolt://localhost:7687"
driver = GraphDatabase.driver(uri, auth=("neo4j", "test"))

p = Pypher()
p.CREATE.node('user', 'User', Name='Jim')

with driver.session() as  session:
    result = session.run(str(p), **dict(p.bound_params))

    print(result)
```

and the result

```
<neo4j.v1.result.BoltStatementResult object at 0x102958940>
```

Maybe it is a version mismatch, I am running 1.5.3 of neo4j

**Comment by g3rd** [comment]
Turns out that I misunderstood how to reference a node, I was doing something like:

```
q = Pypher()
q.Match.node('mark', labels='Person').Create.node(labels='Food', name='Pizza').rel_in(labels='LOVES').mark
```
fixed to:
```
q.Match.node('mark', labels='Person').Create.node(labels='Food', name='Pizza').rel_in(labels='LOVES').node(mark)
```

**Comment by emehrkay** [comment]
I see. One of the things I wanted to add to the project is a quick and dirty repl that would show you the resulting Cypher and params as you typed Pypher. It could be useful in situations like this.

**Comment by emehrkay** [comment]
I added tester.py that will give you a real-time rendering of the expected Cypher query. You need to install prompt-toolkit v2 to use it. Let me know what you thingk
