### ISSUE TITLE
Missing NOT

### ISSUE THREAD

**Issue by g3rd** [emehrkay/Pypher#7]
I don't see in the readme references to `NOT` and `AND NOT`

`.Not` is currently working, it's just not all uppercased on output like the other statements.

```
stmt = Pypher()
stmt.Match.node('u', 'User', username='chad')
stmt.Match.node('u2', 'User', username='sam')
stmt.Where.Not.node('u').rel_out(labels='FOLLOW').node('u2').And.Not.node('u').rel_in(labels='FOLLOW').node('u2')
print(str(stmt))
```
Note: For demonstration purposes not using a `.rel(labels='FOLLOW')`

**Comment by emehrkay** [comment]
Thanks. I was missing a quite a few of them including XOR, IS NULL, IS NOT NULL.

I also fixed a bug that should allow you to dynamically add a statement, before it would print out the word 'STATEMENT'

```python
p.this_is_my_statement(1, 2, 3) # this_is_my_statement 1, 2, 3
```

**Comment by g3rd** [comment]
Thanks @emehrkay for the blazing fast turn around!
