### ISSUE TITLE
Question: Apoc Functions

### ISSUE THREAD

**Issue by g3rd** [emehrkay/Pypher#8]
How would you write:

```
MATCH (u:User {username: 'chad'}) 
WITH apoc.text.join([u.first_name, u.last_name], ' ') AS full_name
RETURN full_name
```

Thanks!

**Comment by emehrkay** [comment]
There are a few ways to do it, this is the first that came to mind:

```python
p.WITH.func_raw('apoc.text.join', __.List(__.u.__first_name__, __.u.__last_name__), "''").alias('full_name')                                    
p.RETURN.full_name 
```

Or you could define the function, this is probably the best case

```python
create_function('apoc_text_join', {'name': 'apoc.text.join'})

p = Pypher()
p.WITH.apoc_text_join(__.List(__.u.__first_name__, __.u.__last_name__), "''").alias('full_name')                                    
```

note: you must double quote the quotes that you want to appear in your resulting Cypher

![screen shot 2018-05-05 at 8 34 49 am](https://user-images.githubusercontent.com/24242/39663327-398def52-503f-11e8-8438-7b366ed9bc0c.png)

**Comment by g3rd** [comment]
@emehrkay this is amazing! Thanks!
